baseURL = "https://agb.com/"
languageCode = "en-us"
title = "Anna's Money Tracker"

[permalinks]
  [permalinks.page]
    tracker = "/tracker/:slug/"

[params]
  description = "Personal expense tracker for AGB"
  author = "Anna"

[build]
  writeStats = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
